project:
  type: website
  output-dir: docs

website:
  title: "Indrajeet Chavan - CPLN 5920 Portfolio"
  navbar:          # ðŸ‘ˆ indentation matters
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: Labs/Labs_0/lab0_IC.qmd
            text: "Lab 0: dplyr Basics"
          - href: Labs/Labs_1/lab1_IC.qmd
            text: "Lab 1: Census Data Exploration"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
